
global:
  seed: 0
  nthetas: 65
  beamformer_input: True
  n_radios: 2

datasets:
  train_paths: 
    - /mnt/md0/spf/2d_wallarray_v2_data/june_fix_nosig/*06*14*7*.zarr
  val_holdout_fraction: 0.2
  val_subsample_fraction: 0.05
  precompute_cache: /home/mouse9911/precompute_cache_chunk16_fresh
  skip_qc: True
  snapshots_per_session: 5
  snapshots_stride: 2
  batch_size: 128
  shuffle: True
  workers: 8

  empirical_data_fn: /home/mouse9911/gits/spf/empirical_dists/full.pkl 
  empirical_individual_radio: False
  empirical_symmetry: True


logger:
  name: simple
  project: train_single_point
  log_every: 100 

model:
  name: beamformer

optim:
  device: cuda
  dtype: torch.float32
  resume_step: 0
  epochs: 10
  val_every: 5000 
  learning_rate: 0.00001
  weight_decay: 0.0000001
  amp: True
