datasets:
  batch_size: 256
  empirical_data_fn:  /home/mouse9911/gits/spf/empirical_dists/full.pkl 
  empirical_individual_radio: false
  empirical_symmetry: true
  flip: false
  double_flip: true
  precompute_cache: /mnt/md2/cache/precompute_cache_3p5_chunk1/
  scatter: continuous
  scatter_k: 21
  shuffle: true
  sigma: 0.1
  skip_qc: true
  snapshots_adjacent_stride: 1
  train_snapshots_per_session: 1
  val_snapshots_per_session: 1
  random_snapshot_size: False
  snapshots_stride: 1
  train_paths:
  - /mnt/md2/splits/feb16_train_nosig_noroverbounce.txt
  val_paths:
  - /mnt/md2/splits/feb16_val_nosig_noroverbounce.txt
  val_holdout_fraction: 0.2
  val_subsample_fraction: 0.2
  workers: 24
  segmentation_version: 3.5
global:
  vehicle_type_input: true
  gains_input: True
  windowed_beamformer_input: true
  signal_matrix_input: false
  beamformer_input: false
  empirical_input: false
  n_radios: 2
  nthetas: 65
  phase_input: false
  rx_spacing_input: true
  frequency_input: true
  seed: 10
logger:
  log_every: 100
  name: wandb
  plot_every: 15000
  project: 2024_nov22_single_paired_multi
model:
  block: true
  bn: true
  depth: 4
  detach: true
  dropout: 0.0
  hidden: 1024
  load_single: true
  name: pairedbeamformer
  norm: layer
  single:
    block: true
    bn: true
    depth: 4
    detach: true
    dropout: 0.0
    hidden: 1024
    input_dropout: 0.2
    name: beamformer
    norm: layer
    windows_stats_net:
      dropout: 0.25
      windowed_beamformer: true
      normalize_windowed_beamformer: false
      hidden_channels: 128
      outputs: 12
      n_layers: 8
      norm: false
      act: leaky
optim:
  amp: false 
  checkpoint: /home/mouse9911/gits/spf/checkpoints/feb16/single_wd0p02_gains_vehicle_0p2dropout_noroverbounce/best.pth
  checkpoint_every: 5000
  device: cuda
  direct_loss: false
  dtype: torch.float32
  epochs: 60
  head_start: 0
  learning_rate: 0.0002
  loss: mse
  resume_step: 0
  output: /home/mouse9911/gits/spf/checkpoints/feb16/paired_checkpoints_windowedbeamformer_nosig_3p5_randx_wd0p02_gains_vehicle_0p2dropout_noroverbounce
  save_on: val/paired_loss
  scheduler_step: 12
  val_every: 10000
  weight_decay: 0.0
