
global:
  seed: 10
  nthetas: 65
  beamformer_input: True
  n_radios: 2

datasets:
  train_paths: 
    - /home/mouse9911/nosig_data/june_fix_nosig/*06*.zarr
  val_holdout_fraction: 0.2
  val_subsample_fraction: 0.05
  precompute_cache: /home/mouse9911/precompute_cache_chunk16_sept
  skip_qc: True
  snapshots_per_session: 2
  snapshots_stride: 2
  batch_size: 256
  shuffle: True
  workers: 20
  sigma: 0.0
  scatter_k: 1

  empirical_data_fn: /home/mouse9911/gits/spf/empirical_dists/full.pkl 
  empirical_individual_radio: False
  empirical_symmetry: True


logger:
  name: wandb
  project: train_single_point_sept15
  log_every: 100 

model:
  name: beamformer
  hidden: 512
  depth: 32
  block: True
  bn: False
  norm: False

optim:
  device: cuda
  dtype: torch.float32
  resume_step: 0
  epochs: 20
  val_every: 1000 
  learning_rate: 0.00001
  weight_decay: 0.0000001
  amp: False
