run_EKF_single_theta_single_radio:
  phi_std: [10.0, 5.0, 2.5]
  p: [10.0, 5.0, 2.5, 1.0]
  noise_std: [0.1, 0.01, 0.001, 0.0001]
  dynamic_R: [True, False]

run_EKF_single_theta_dual_radio:
  phi_std: [10.0, 5.0, 2.5]
  p: [10.0, 5.0, 2.5, 1.0]
  noise_std: [0.1, 0.01, 0.001, 0.0001]
  dynamic_R: [True, False]

run_EKF_xy_dual_radio:
  phi_std: [10.0, 5.0, 2.5, 1.0]
  p: [10.0, 5.0, 2.5, 1.0]
  noise_std: [20.0, 10.0, 5.0]
  dynamic_R: [True, False]

run_PF_single_theta_single_radio:
  N: [128, 128 * 4, 128 * 8, 128 * 16]
  theta_err: [0.1, 0.01, 0.001, 0.2]
  theta_dot_err: [0.1]

run_PF_single_theta_dual_radio:
  N: [128, 128 * 4, 128 * 8, 128 * 16]
  theta_err: [0.1, 0.01, 0.001, 0.2]
  theta_dot_err: [0.1]

run_PF_xy_dual_radio:
  N: [128, 128 * 4, 128 * 8, 128 * 16, 128 * 32]
  pos_err: [1000, 100, 50, 30, 15, 5, 0.5]
  vel_err: [50]
