#!/usr/bin/env bash
#
# Configure a rover's static eth0 address, hostname, and wifi state.
#
# Replaces the two ungated board blocks in setup.sh, which assume a single
# Raspberry Pi OS image layout and are wrong on newer images in two ways:
#
#   1. They write /etc/network/interfaces, which is inert without ifupdown.
#      The 2026 bookworm Lite image does not ship ifupdown.
#   2. They write /boot/config.txt, which on that image is a stub reading
#      "DO NOT EDIT THIS FILE - moved to /boot/firmware/config.txt". Appending
#      dtoverlay=disable-wifi there leaves wifi ENABLED and corrupts the stub.
#
# This script detects both and writes whichever file is real.
#
# Address = 192.168.1.(40 + rover_id), matching setup.sh. Reserve it in the
# router's DHCP pool first: the rover addresses sit inside the pool and IP
# squatting while a rover is off has been observed (ROVER_RUNBOOK.md section 2).
#
# Stages, deliberately separate so the irreversible one comes last:
#
#   static-only   set hostname + static eth0. Wifi is left UP. Idempotent.
#   verify        report whether the static address is live. Read-only.
#   disable-wifi  append dtoverlay=disable-wifi to the REAL config file.
#                 REFUSES unless the static address already answers, so the
#                 rover is never left with no reachable path.
#   rollback      undo static-only (remove interfaces file, restore DHCP).
#
# Usage:
#   sudo ./configure_rover_network.sh 4 --stage static-only
#        ./configure_rover_network.sh 4 --stage verify
#   sudo ./configure_rover_network.sh 4 --stage disable-wifi
#   sudo ./configure_rover_network.sh 4 --stage rollback
#
set -euo pipefail

die() { printf 'configure_rover_network: %s\n' "$*" >&2; exit 1; }
note() { printf '  %s\n' "$*"; }

[[ $# -ge 1 ]] || die "usage: $0 ROVER_ID --stage {static-only|verify|disable-wifi|rollback}"
rover_id="$1"; shift
[[ "$rover_id" =~ ^[1-4]$ ]] || die "Unsupported rover_id: ${rover_id}"

stage=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --stage) stage="${2:-}"; shift 2 ;;
        *) die "unknown argument: $1" ;;
    esac
done
[[ -n "$stage" ]] || die "--stage is required"

octet=$((40 + rover_id))
address="192.168.1.${octet}"
gateway="192.168.1.1"
dns="8.8.8.8"
hostname_want="roverpi${rover_id}"
iface="eth0"

# --- image-layout detection ------------------------------------------------
# The authoritative config.txt is whichever one the firmware reads. On older
# images /boot/config.txt is a symlink to /boot/firmware/config.txt; on newer
# ones it is a stub telling you not to edit it.
detect_boot_config() {
    if [[ -L /boot/config.txt ]]; then
        readlink -f /boot/config.txt
    elif [[ -f /boot/firmware/config.txt ]]; then
        echo /boot/firmware/config.txt
    elif [[ -f /boot/config.txt ]]; then
        echo /boot/config.txt
    else
        die "no config.txt found in /boot or /boot/firmware"
    fi
}

# Test the package, not the PATH: /sbin is not in the pi user's PATH over ssh,
# so `command -v ifup` reports absent on rover 1 where ifupdown IS installed.
have_ifupdown() {
    [[ "$(dpkg-query -W -f='${Status}' ifupdown 2>/dev/null)" == "install ok installed" ]]
}

static_is_live() {
    ping -c1 -W2 "$address" >/dev/null 2>&1
}

# --- stages ----------------------------------------------------------------
case "$stage" in

verify)
    note "rover_id        : ${rover_id}"
    note "expected address: ${address}"
    note "hostname        : $(hostname) (want ${hostname_want})"
    note "boot config     : $(detect_boot_config)"
    note "ifupdown        : $(have_ifupdown && echo present || echo absent)"
    note "eth0 addrs      : $(ip -brief addr show "$iface" 2>/dev/null | awk '{$1="";$2="";print}' | xargs || echo none)"
    note "wlan0           : $(ip link show wlan0 >/dev/null 2>&1 && echo present || echo absent)"
    if static_is_live; then note "static ${address}: LIVE"; else note "static ${address}: NOT reachable"; fi
    ;;

static-only)
    [[ $EUID -eq 0 ]] || die "static-only must run as root"

    if [[ "$(hostname)" != "$hostname_want" ]]; then
        note "hostname $(hostname) -> ${hostname_want}"
        hostnamectl set-hostname "$hostname_want"
        # 127.0.1.1 must track the hostname or sudo emits resolver warnings
        if grep -qE '^127\.0\.1\.1' /etc/hosts; then
            sed -i -E "s/^(127\.0\.1\.1[[:space:]]+).*/\1${hostname_want}/" /etc/hosts
        else
            printf '127.0.1.1\t%s\n' "$hostname_want" >>/etc/hosts
        fi
    else
        note "hostname already ${hostname_want}"
    fi

    if have_ifupdown; then
        note "ifupdown present - using /etc/network/interfaces (matches rover 1)"
    else
        note "ifupdown absent - installing it so this rover matches rover 1"
        apt-get update -qq
        apt-get install -y -qq ifupdown
        have_ifupdown || die "ifupdown install failed; refusing to continue"
    fi

    # NetworkManager on these images already ships plugins=ifupdown,keyfile with
    # [ifupdown] managed=false, so defining eth0 here makes NM release it. Verified
    # identical on rover 1 and rover 4; assert rather than assume.
    if ! grep -qE '^\s*plugins=.*ifupdown' /etc/NetworkManager/NetworkManager.conf 2>/dev/null; then
        die "NetworkManager.conf lacks the ifupdown plugin; eth0 would stay NM-managed"
    fi

    note "writing /etc/network/interfaces for ${address}/24"
    cat >/etc/network/interfaces <<EOF
source /etc/network/interfaces.d/*

auto ${iface}
iface ${iface} inet static
    address ${address}/24
    gateway ${gateway}
    dns-nameservers ${dns}
EOF

    # DNS must be a static /etc/resolv.conf, matching rover 1. The
    # `dns-nameservers` line above only takes effect via the resolvconf package,
    # which is NOT installed on rover 1 either - rover 1 simply has a plain
    # static resolv.conf. Without this, once eth0 moves to ifupdown,
    # NetworkManager stops supplying DNS and leaves an empty
    # "# Generated by NetworkManager" stub, so apt/git fail to resolve.
    if ! grep -qE '^\s*nameserver\s' /etc/resolv.conf 2>/dev/null; then
        note "writing static /etc/resolv.conf (${dns} + 1.1.1.1), matching rover 1"
        [[ -f /etc/resolv.conf ]] && cp -a /etc/resolv.conf /etc/resolv.conf.bak 2>/dev/null || true
        rm -f /etc/resolv.conf   # may be a symlink into NM/systemd-resolved
        printf 'nameserver %s\nnameserver 1.1.1.1\n' "$dns" >/etc/resolv.conf
    else
        note "/etc/resolv.conf already has a nameserver - left alone"
    fi

    systemctl restart NetworkManager || true
    # Absolute path: sudo's secure_path usually covers /sbin, but not always.
    ifup_bin="$(command -v ifup || echo /sbin/ifup)"
    "$ifup_bin" "$iface" 2>/dev/null || true
    sleep 3
    note "eth0 now: $(ip -brief addr show "$iface" | awk '{$1="";$2="";print}' | xargs)"
    note ""
    note "NEXT: from another machine, prove the address before disabling wifi:"
    note "  ssh pi@${address} 'hostname; ip -brief addr show eth0'"
    ;;

disable-wifi)
    [[ $EUID -eq 0 ]] || die "disable-wifi must run as root"

    # The whole point of the stage split: never remove the fallback path until
    # the replacement path is known good.
    static_is_live || die "refusing: ${address} does not answer ping. Run --stage static-only, verify it, then retry."

    boot_config="$(detect_boot_config)"
    note "authoritative boot config: ${boot_config}"
    [[ ! -f /boot/config.txt || -L /boot/config.txt || "$boot_config" == "/boot/config.txt" ]] && true
    if [[ -f /boot/config.txt && ! -L /boot/config.txt && "$boot_config" != "/boot/config.txt" ]]; then
        note "note: /boot/config.txt is a stub on this image and is deliberately NOT written"
    fi

    if grep -qE '^\s*dtoverlay=disable-wifi' "$boot_config"; then
        note "dtoverlay=disable-wifi already present - nothing to do"
    else
        cp -a "$boot_config" "${boot_config}.bak.$(date +%s 2>/dev/null || echo prev)"
        printf 'dtoverlay=disable-wifi\n' >>"$boot_config"
        note "appended dtoverlay=disable-wifi"
    fi
    note "tail: $(tail -1 "$boot_config")"
    note ""
    note "NEXT: reboot, then confirm ${address} returns and wlan0 is gone."
    ;;

rollback)
    [[ $EUID -eq 0 ]] || die "rollback must run as root"
    note "removing /etc/network/interfaces and returning eth0 to NetworkManager"
    rm -f /etc/network/interfaces
    systemctl restart NetworkManager || true
    sleep 3
    note "eth0 now: $(ip -brief addr show "$iface" | awk '{$1="";$2="";print}' | xargs)"
    note "wifi config untouched by this stage"
    ;;

*)
    die "unknown stage: ${stage}"
    ;;
esac
