#!/bin/bash
#
# DEPRECATED 2026-08-03 — DO NOT RUN. Use provision_rover.sh instead.
#
# Kept as a historical reference only: the firmware/parameter URLs and the
# original ordering are still useful context. Everything it does is now done by
# provision_rover.sh, correctly and idempotently.
#
# It is unsafe on current Raspberry Pi OS images:
#
#   1. Both board blocks run UNGATED. It writes /etc/network/interfaces AND the
#      systemd-networkd unit, and edits both /boot/config.txt and
#      /boot/firmware/config.txt, on every board.
#   2. Its Pi-4 wifi block writes /boot/config.txt, which on 2024+ images is a
#      stub reading "DO NOT EDIT THIS FILE". Wifi stays ENABLED and the stub is
#      corrupted.
#   3. Its Pi-4 network block writes /etc/network/interfaces, which is inert
#      without ifupdown — absent from the 2026 Lite image.
#   4. It disables wifi and reboots BEFORE the static address is ever proven, so
#      a failure strands the rover with no reachable path.
#   5. It clones the repo (line ~15) before install_deps.sh installs git
#      (line ~17), which cannot work on an image that ships without git.
#   6. It flashes plutosdr-fw-v0.37-dirty from Dropbox, which predates the
#      direct-USB gain/RSSI campaign. Production firmware is now pinned in the
#      canonical capture config and installed by configure_direct_usb_boot.sh.
#   7. It is not idempotent or resumable: a re-run fails at git clone.
#
# See data_collection/rover/rover_v3.1/rover4_setup.md for the full rationale
# and the provisioning runbook.

cat >&2 <<'DEPRECATED'
ERROR: setup.sh is DEPRECATED and unsafe on current Raspberry Pi OS images.

  Use:  sudo ./provision_rover.sh <ROVER_ID> --stage <stage>
  Docs: rover4_setup.md

Refusing to run. See the comment block at the top of this file for why.
DEPRECATED
exit 1

if [ $# -ne 1 ]; then
        echo $0 ROVER_ID
        exit
fi

#assign the rover its ID
repo_root="/home/pi/spf/"

rover_id=$1
echo ${rover_id} > ~/rover_id

cd /home/pi
git clone https://github.com/misko/spf.git

bash ${repo_root}/data_collection/rover/rover_v3.1/install_deps.sh

#sudo apt-get update
#sudo apt-get install git screen libiio-dev libiio-utils vim python3-dev uhubctl libusb-dev libusb-1.0-0-dev sshpass -y

# virtual enviornment setup
python -m venv ~/spf-virtualenv
source ~/spf-virtualenv/bin/activate

cd spf
#pip install -r requirements.txt
pip install -e . 
pip install RPi.GPIO

grep -v spf ~/.bashrc | grep -v lsusb  > /tmp/bashrc && mv /tmp/bashrc ~/.bashrc
echo export PYTHONPATH=/home/pi/spf >> ~/.bashrc
echo 'test -z "$VIRTUAL_ENV" && source ~/spf-virtualenv/bin/activate' >> ~/.bashrc

####PI 4####

echo "lsusb -t | grep usb-storage | sed 's/.*Port \([0-9]*\): Dev \([0-9]*\),.*/\1 \2/g' > ~/device_mapping" >> ~/.bashrc
# lets get eth0 to static ip
cat > interfaces <<- EOM
source /etc/network/interfaces.d/*

auto eth0
iface eth0 inet static
    address 192.168.1.__ROVERID__/24
    gateway 192.168.1.1
EOM
sed -i "s/__ROVERID__/$(expr 40 + ${rover_id})/g" interfaces
sudo cp -f interfaces /etc/network/interfaces

# disable wifi so it wont interfere
grep -v disable-wifi /boot/config.txt > /tmp/config.txt && sudo cp /tmp/config.txt /boot/config.txt # /boot/firmware/config.txt (pi5)
sudo sh -c 'echo dtoverlay=disable-wifi >> /boot/config.txt' # /boot/firmware/config.txt pi5

### END PI 4 ####




####PI 5####
sudo apt-get install systemd-resolved
echo "lsusb  | grep PLUTO | awk '{print int(\$2)%3\" \"int(\$2)\" \"int(\$4) }' > ~/device_mapping" >> ~/.bashrc
# lets get eth0 to static ip
cat > interfaces <<- EOM
[Match]
Name=eth0

[Network]
Address=192.168.1.__ROVERID__/24
Gateway=192.168.1.1
DNS=8.8.8.8
EOM
sed -i "s/__ROVERID__/$(expr 40 + ${rover_id})/g" interfaces
sudo cp -f interfaces /etc/systemd/network/10-eth0.network
sudo systemctl enable systemd-networkd
sudo systemctl start systemd-networkd

# disable wifi so it wont interfere
grep -v disable-wifi /boot/firmware/config.txt > /tmp/config.txt && sudo cp /tmp/config.txt /boot/firmware/config.txt # /boot/firmware/config.txt (pi5)
sudo sh -c 'echo dtoverlay=disable-wifi >> /boot/firmware/config.txt' # pi5

#echo 8.8.8.8 | sudo tee /etc/resolv.conf 
sudo systemctl disable NetworkManager

### END PI 5 ####





# add USB permissions for all users
grep -v usb_device /etc/udev/rules.d/99-com.rules > /tmp/99-com.rules && sudo cp /tmp/99-com.rules /etc/udev/rules.d/99-com.rules
sudo sh -c 'echo SUBSYSTEM=="usb_device", MODE="0664", GROUP="usb" >> /etc/udev/rules.d/99-com.rules'

# flash pluto
# sudo chmod -R 777 /dev/bus/usb/ # allow all USB access

pluto_fw=plutosdr-fw-v0.37-dirty.zip

while [ 1 -lt 2 ]; do
        wget -O ${pluto_fw} 'https://www.dropbox.com/s/4jji77rk3d9ikba/plutosdr-fw-v0.37-dirty.zip?dl=0'
        md5='613fcdd4f45ad695d85abd53d1e0b918'
        current_md5=`md5sum ${pluto_fw} | awk '{print $1}'`
        if [ "$md5" == "${current_md5}" ]; then
                echo "Download succesful!"
                break
        fi
        rm -f ${pluto_fw}
done


mounts='/dev/sda /dev/sdb'
mount_point='/media/pluto'
if [ ! -d "${mount_point}" ]; then
        sudo mkdir -p ${mount_point}
fi
for mount in $mounts; do 
        if [ -b "$mount" ]; then
                echo "Trying to flash $mount"
                sudo mount "${mount}1" ${mount_point}
                sudo cp ${pluto_fw} ${mount_point}
                sudo eject ${mount}
                sleep 1
                echo -n "Waiting for device to come back up"
                while [ ! -b "${mount}1" ]; do
                        echo -n "."
                        sleep 5
                done
                echo "Device came back up!, flashing complete"
        fi
done


# flash rover
#sudo uhubctl  -a 0
#sleep 2
#sudo uhubctl  -a 1
#sleep 2
sudo systemctl stop mavlink_controller.service # might fail but just in case
sleep 5
wget https://raw.githubusercontent.com/ArduPilot/ardupilot/master/Tools/scripts/uploader.py
#wget https://firmware.ardupilot.org/Rover/stable-4.4.0/fmuv3/ardurover.apj
wget https://firmware.ardupilot.org/Rover/stable-4.5.0/fmuv3/ardurover.apj
#wget https://firmware.ardupilot.org/Rover/stable-4.4.0/fmuv2/ardurover.apj
python uploader.py ardurover.apj | tee > ardurover_flash.log
sleep 5
#cmd for mavproxy does not work
# go in by hand and do this a few times
#     param set FORMAT_VERSION 0
#     param show FORMAT_VERSION
#  then
#     reboot
# and restart mavproxy

#mavproxy.py  --cmd 'set requireexit True; param set FORMAT_VERSION 0; reboot; exit; exit;' # reset to default parameters
#sleep 5
#load these a few times, 
#should see HOLD> Loaded 256 parameters from this_rover.params (changed 0)


#mkfifo tmp_file
#cat tmp_file |  mavproxy.py &

# Production services and the firmware asset are installed from the canonical
# Rover V7 config selected by /home/pi/rover_id.
# Persistent AD9361/2R2T provisioning is explicit and happens only here. On an
# ordinary boot, firmware preparation reads the active version and is read-only
# when it matches; only an explicit mismatch enters the QSPI update path.
sudo /home/pi/spf/data_collection/rover/rover_v3.1/check_and_set_pluto.sh \
    --apply
sudo /home/pi/spf/data_collection/rover/rover_v3.1/configure_direct_usb_boot.sh \
    production-default

mkdir -p /home/pi/arduino
pushd /home/pi/arduino
curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
popd
echo export PATH=${PATH}:/home/pi/arduino/bin >> ~/.bashrc
/home/pi/arduino/bin/arduino-cli config init
/home/pi/arduino/bin/arduino-cli config add board_manager.additional_urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
/home/pi/arduino/bin/arduino-cli core update-index

# Trim stock services that add boot time and, in ModemManager's case, actively
# destabilize USB enumeration on a headless field rover. All safe: the rover has
# no cellular modem or Bluetooth peripheral, must never auto-update its boot
# EEPROM (and can't, offline), and its rootfs is not LVM (e2scrub). Masking
# NetworkManager-wait-online keeps network-online.target off the boot critical
# path without deconfiguring the static eth0 (SSH/LAN unaffected). These are also
# safe to run by hand on an already-provisioned rover.
# - ModemManager AT-probes the ArduPilot /dev/ttyACM* and the Pluto CDC gadget
#   during the exact window the RAM-load re-enumerates -> a plausible contributor
#   to intermittent "expected N Plutos, found N-1" failures.
sudo systemctl disable --now ModemManager.service 2>/dev/null || true
sudo systemctl disable --now bluetooth.service 2>/dev/null || true
sudo systemctl disable --now rpi-eeprom-update.service 2>/dev/null || true
sudo systemctl disable --now e2scrub_reap.service 2>/dev/null || true
sudo systemctl mask NetworkManager-wait-online.service 2>/dev/null || true

#will come back up with new static IP
sudo reboot


# (spf-virtualenv) pi@roverpi2:~/spf/spf $ sudo iio_info -s
# Library version: 0.24 (git tag: v0.24)
# Compiled with backends: local xml ip usb
# Unable to create Local IIO context : No such file or directory (2)
# Available contexts:
#         0: 192.168.1.18 (Analog Devices PlutoSDR Rev.C (Z7010-AD9363A)), serial=1040007c4a94000211000b009186843ef2 [ip:pluto-2.local]
#         1: 192.168.1.17 (Analog Devices PlutoSDR Rev.C (Z7010-AD9363A)), serial=104000bac4950008230026001b440a003a [ip:pluto.local]
#         2: 192.168.2.1 (Analog Devices PlutoSDR Rev.C (Z7010-AD9363A)), serial=104000943807000a220011008101b882a9 [ip:pluto.local]
#         3: 0456:b673 (Analog Devices Inc. PlutoSDR (ADALM-PLUTO)), serial=104000943807000a220011008101b882a9 [usb:1.3.5]


# USB URI is usb:1.3.5

# #to allow users to access usb devices
# 
# # there is some examples online using udev but those are not owkring
